### PR TITLE
Add Launch in Deepnote button

### PR DESCRIPTION
**Pull request by jakubzitny**
Hi, [Deepnote](https://deepnote.com/) just added a possibility to install custom environments and also documented usage with [Almond](https://docs.deepnote.com/environment/custom-environments/running-your-own-kernel#scala-2-12-12-kernel-almond-0-10-9). I'd say it's a pretty good addition to Binder and NBviewer ;)

Disclaimer: I am a core member of Deepnote team.

### CODE REVIEW

**Comment by sbrunk** [comment]
Looks good to me. WDYT @alexarchambault?

I see that the almond and examples repo appear as a subfolder in your Deepnote project. Are they kept up to date with master automatically or how does the linking work?

**Comment by alexarchambault** [comment]
> Looks good to me. WDYT @alexarchambault?

That seems to work great, yes. Thanks @jakubzitny!

FYI, I ran into one minor glitch when cloning the project (via the "Duplicate" button): upon cloning, the opened notebook becomes the one named "akka" at the root of the project, rather than "index" from the examples. One has to know the path of the examples index to find it back in the files tab. Apart from that, everything seemed to work great.

**Comment by jakubzitny** [comment]
Good point, I fixed it - created a new index in the root which links to the examples. I kept the Akka notebook to be accessible as well, all notebooks and files are available in the Files sidebar.

@sbrunk, this project is not linked, it's just a clone. But anyone can duplicate the project and update. For regular python kernels we do have the possibility to just link a GitHub repo and when "launched" it is always up to date. But for Scala kernels, we have to use a custom Dockerfile, so the whole environment is set up properly. We'd have to include the Dockerfile in this repo, and I'd have to test it. Should I do that? :)

**Comment by sbrunk** [comment]
@jakubzitny I think we can add the link as is for now. It would still be interesting to be able to launch an always up-to-date Deepnote env at some point though. So if you find the time to test the setup with a Dockerfile perhaps on a fork and than create a PR that would be great.

**Comment by jakubzitny** [comment]
Perfect, we're actually figuring out the best way to do this, and I think we'll be able to create a solution on our side without having Dockerfile in this repo. Will update the link once we have it ready.

**Pull request merged**
