### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by sbrunk**
As suggested in #5, the easiest way here would probably to use dockerhub for building the image on a push to master. What do you think @alexarchambault?

We can still add it to the main CI build later instead if that makes more sense at some point.

### CODE REVIEW

**Comment by sbrunk** [comment]
@alexarchambault could you add the dockerhub repo for this (linked to this repo with a build rule that builds on push to master and tags just latest)? I don't want to merge it before because the `git pull` in the readme doesn't work without that.

**Comment by alexarchambault** [comment]
Just adjusted the dockerhub settings. Let's see how it goes.

**Comment by alexarchambault** [comment]
Sorry for the delay by the way :|

**Comment by sbrunk** [comment]
I think you have added it to the main almond docker repo `almondsh/almond`? I thought it might be better to create a dedicated docker repo `almondsh/examples`.

Otherwise because people might be confused because they expect ` almondsh/almond:latest` to contain just the current almond version. I.e. the same as ` almondsh/almond:0.4.0` at the moment.

Sorry I probably should have communicated what I meant more clearly.

**Comment by alexarchambault** [comment]
Ok, I got confused by the fact that the build of the main image used to be done from dockerhub…

The new repo is [here](https://hub.docker.com/r/almondsh/examples), and its build is ongoing.

**Comment by sbrunk** [comment]
Thanks. The build is finished now and it seems to works fine. :)

I'll add a line about it to the docker page in the main docs.

**Pull request merged**
