### PR TITLE
TransmogrifAI examples

### PR DESCRIPTION
**Pull request by sbrunk**
Adds example notebooks for TransmogrifAI based on https://github.com/salesforce/TransmogrifAI/tree/master/helloworld/notebooks.

Draft because there's still an issue when creating workflows I haven't been able to solve yet. I.e. in cell 14 in  [OpIris.ipynb](https://github.com/sbrunk/examples/blob/transmogrifai/notebooks/TransmogrifAI/OpIris.ipynb).

```scala
val workflow = new OpWorkflow().setResultFeatures(prediction, labels).setReader(trainDataReader)
```

```
java.lang.IllegalArgumentException: requirement failed: No matching data readers for 5 input features: Feature(name = irisClass, uid = Text_000000000005, isResponse = true, originStage = FeatureGeneratorStage_000000000005, parents = [], distributions = []),Feature(name = petalLength, uid = Real_000000000003, isResponse = false, originStage = FeatureGeneratorStage_000000000003, parents = [], distributions = []),Feature(name = petalWidth, uid = Real_000000000004, isResponse = false, originStage = FeatureGeneratorStage_000000000004, parents = [], distributions = []),Feature(name = sepalLength, uid = Real_000000000001, isResponse = false, originStage = FeatureGeneratorStage_000000000001, parents = [], distributions = []),Feature(name = sepalWidth, uid = Real_000000000002, isResponse = false, originStage = FeatureGeneratorStage_000000000002, parents = [], distributions = []). Readers had types: cmd12.this.cmd2.Iris
  com.salesforce.op.OpWorkflowCore$class.checkUnmatchedFeatures(OpWorkflowCore.scala:227)
  com.salesforce.op.OpWorkflow.checkUnmatchedFeatures(OpWorkflow.scala:59)
  com.salesforce.op.OpWorkflowCore$class.setReader(OpWorkflowCore.scala:123)
  com.salesforce.op.OpWorkflow.setReader(OpWorkflow.scala:59)
  ammonite.$sess.cmd13$Helper.<init>(cmd13.sc:1)
  ammonite.$sess.cmd13$.<init>(cmd13.sc:7)
  ammonite.$sess.cmd13$.<clinit>(cmd13.sc:-1)
```

### CODE REVIEW

**Comment by alexarchambault** [comment]
I managed to have OpIris work… 

The trick is either to manually wrap (the whole cell of) the definition of the `Iris` case class in an object, to disable class-wrapping for it, like
```scala
object Definitions {
  org.apache.spark.sql.catalyst.encoders.OuterScopes.addOuterScope(this)
  case class Iris(
    sepalLength: Double,
    sepalWidth: Double,
    petalLength: Double,
    petalWidth: Double,
    irisClass: String
  )
}
```
then import `Definitions._` in a subsequent cell, or create a `WeakTypeTag` along the iris defintion, like
```scala
org.apache.spark.sql.catalyst.encoders.OuterScopes.addOuterScope(this)
case class Iris
(
  sepalLength: Double,
  sepalWidth: Double,
  petalLength: Double,
  petalWidth: Double,
  irisClass: String
)
implicit val irisTypeTag = scala.reflect.runtime.universe.weakTypeTag[Iris]
```

The issue originates from the "class wrapping" stuff (wrapping user code in classes rather than objects, for Java serialization, handled in Ammonite and enabled by default in almond), which seems to confuse some code in transmogrifai, that [compares the string representation of some types it gets via reflection](https://github.com/salesforce/TransmogrifAI/blob/2566a0867b98d7eac7319231fbf600f3480a8da3/core/src/main/scala/com/salesforce/op/OpWorkflowCore.scala#L232). Class-wrapping involves some path-dependent stuff, which changes those strings for the same type from cell to cell… Creating the `WeakTypeTag` once "fixes" it to one cell, and the string doesn't change anymore…

I'm not sure why this isn't a problem with the default scala repl, when class-wrapping is enabled in it…

**Comment by alexarchambault** [comment]
Also, I recommend silencing the logs of breeze too (`Logger.getLogger("breeze").setLevel(Level.OFF)`), which basically flood and freeze the client else. (I'd like to have these logs [sent to the browser console](https://github.com/almond-sh/almond/blob/ef6c16ab66f9cd95dee644c0af009df7281c40ba/modules/scala/almond-spark/src/main/scala/org/apache/spark/sql/almondinternals/SendLog.scala).)

**Comment by sbrunk** [comment]
Thanks! I only got it working by putting the `FeatureBuilder` defintions into one cell with the workflow execution. But this is a much better. I'll update the notebooks accordingly.

The Titanic example works too. But since it has many small RDD operations, the output is flooded with progress bars so I guess we have some room for improvement here.

grafik

**Comment by alexarchambault** [comment]
Forgot about this one. I passed `.progress(false)` to `NotebookSessionBuilder` to disable them, like
```scala
import org.apache.spark.sql._

implicit val spark = {
  NotebookSparkSession.builder()
    .progress(false)
    .master("local[*]")
    .getOrCreate()
}
```

`progress` is defined [around here](https://github.com/almond-sh/almond/blob/994798a1ecbd5169d212a30a5661a2a93e62f4ed/modules/scala/almond-spark/src/main/scala/org/apache/spark/sql/almondinternals/NotebookSparkSessionBuilder.scala#L29).

`.progress(keep = false)` ought to have worked too (displaying progress bars, but discarding them once they reach 100%), but it doesn't discard the labels right above the progress bars for now, so the output gets flooded by those anyway…

**Comment by sbrunk** [comment]
Let's re-add `.progress(keep = false)` once cleaning up the progress bars works.

I couldn't get it working by wrapping it in a `Definitions` object BTW. Using a `WeakTypeTag` works fine for me.

**Review by alexarchambault — APPROVED** [review]

**Comment by sbrunk** [comment]
/cc @rajdeepd @leahmcguire @tovbinm to let you know that we've adaped the examples for almond and added them here.

You can also [run them without any setup via binder](https://mybinder.org/v2/gh/almond-sh/examples/master?urlpath=lab%2Ftree%2Fnotebooks%2FTransmogrifAI%2FOpIris.ipynb).

**Comment by tovbinm** [comment]
Nice! @sbrunk

Wanna add a section referencing this work into our docs as well? https://github.com/salesforce/TransmogrifAI/tree/master/docs/examples

**Pull request merged**
